### ISSUE TITLE
Encounter a GuzzleHttp\Exception\RequestException in PortalLoginController@handleProviderCallback

### ISSUE THREAD

**Issue by sShaAanGg** [ncucc/laravel-socialite-portal-provider#1]
大家好，我正在替工學院建立一個內部的系統，打算透過 portal 來處理 authentication 的問題，照著 [README.md](https://github.com/ncucc/laravel-socialite-portal-provider#readme) 以及 [Laravel Docs](https://laravel.com/docs/8.x/socialite) 加入相關檔案。
開始測試後發現在 handleProviderCallback 內部會產生一系列呼叫，最終產生一個 GuzzleHttp\Exception\RequestException。 以下為登入授權後重導向頁面顯示的訊息

`cURL error 60: SSL certificate problem: certificate has expired (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://portal.ncu.edu.tw/oauth2/token`

版本資訊:
```
"require": {
        "php": "^7.3|^8.0",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8.40",
        "laravel/jetstream": "^2.3",
        "laravel/sanctum": "^2.6",
        "laravel/socialite": "^5.5",
        "laravel/tinker": "^2.5",
        "livewire/livewire": "^2.0",
        "maatwebsite/excel": "^3.1",
        "ncucc/portal-oauth2-provider": "dev-master",
        "spatie/laravel-permission": "^4.2"
}
```

想請教一下關於此問題有甚麼可能的解決方法或方向，感謝各位的耐心協助

**Comment by linuzilla** [comment]
### 問題原因：
Portal 採用的 Let's Encrypt 是由 ISRG Root X1 及 DST Root CA X3 兩張憑證所簽署的。這原因是因為 ISRG Root X1 是比較新的憑證，為了避免在舊的裝置不能被信任，所以由 DST Root CA X3 做交錯簽署。但 DST Root CA X3 的有效期限到 2021 年  9 月。
### 解決方法：
解決方式如下，依次序，若解決就不用再往下

1. 更新你的作業系統。目前這是最簡單的解法，除非你的系統無法更新。
2. 更新系統如果無法解決的話，可能要手動移掉 Root CA 上那張 DST Root CA X3 的憑證（如果存在的話），因為 curl 的 library 一發現這張過期了，就不會檢查其實 ISRG Root X1 是合法的。(Redhat/CentOS/Rocky 參考路徑為 /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem)
3. 如果你的系統太舊，最後的解決方法是讓 GuzzleHttp 在連線時忽略憑證的部份。

**Comment by sShaAanGg** [comment]
> ### 問題原因：
> 
> Portal 採用的 Let's Encrypt 是由 ISRG Root X1 及 DST Root CA X3 兩張憑證所簽署的。這原因是因為 ISRG Root X1 是比較新的憑證，為了避免在舊的裝置不能被信任，所以由 DST Root CA X3 做交錯簽署。但 DST Root CA X3 的有效期限到 2021 年 9 月。
> ### 解決方法：
> 
> 解決方式如下，依次序，若解決就不用再往下
> 
>     1. 更新你的作業系統。目前這是最簡單的解法，除非你的系統無法更新。
> 
>     2. 更新系統如果無法解決的話，可能要手動移掉 Root CA 上那張 DST Root CA X3 的憑證（如果存在的話），因為 curl 的 library 一發現這張過期了，就不會檢查其實 ISRG Root X1 是合法的。(Redhat/CentOS/Rocky 參考路徑為 /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem)
> 
>     3. 如果你的系統太舊，最後的解決方法是讓 GuzzleHttp 在連線時忽略憑證的部份。

了解，感謝
